### ISSUE TITLE
Summing up not equal to 1

### ISSUE THREAD

**Issue by LeiYangJustin** [HeddaCohenIndelman/Learning-Gumbel-Sinkhorn-Permutations-w-Pytorch#3]
Hi Hedda, 

Have you noticed that each row or col may not actually add up to 1?

**Comment by HeddaCohenIndelman** [comment]
Hello, 
Please note that as in the paper, a truncated Sinkhorn operator is used where the number of normalization steps are predetermined (parameter n_iter_sinkhorn ). 
Note also that the in theory Sinkhorn operator results in a doubly stochastic matrix **in the limit.** In practice, most practitioners limit the number of iterations (hence truncated version).   
I set n_iter_sinkhorn =20 as done in the paper, you can try increasing it and see if you get better results.
Hedda.

**Comment by LeiYangJustin** [comment]
> Hello,
> Please note that as in the paper, a truncated Sinkhorn operator is used where the number of normalization steps are predetermined (parameter n_iter_sinkhorn ).
> Note also that the in theory Sinkhorn operator results in a doubly stochastic matrix **in the limit.** In practice, most practitioners limit the number of iterations (hence truncated version).
> I set n_iter_sinkhorn =20 as done in the paper, you can try increasing it and see if you get better results.
> Hedda.

Hi Hedda, thanks your reply. Mine converges at a later stage. It is just because in the very beginning the entries in the matrix to be approximated are quite close to each other that leads to non-convergence. Thanks.

**Comment by LeiYangJustin** [comment]
Hi Hedda, thanks for your reply. I found my perm matrix eventually converges.

**Comment by HeddaCohenIndelman** [comment]
Great.
